CREATE DATABASE crusin66;

USE crusin66;

-- DROP TABLE IF EXISTS users;


CREATE TABLE users (
  userId INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(25) NOT NULL,
  lastName VARCHAR(25) NOT NULL,
  userName VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  createDate TIMESTAMP,
  updateDate TIMESTAMP
);

